[package]
name = "value_note"
authors = ["aztec-labs"]
compiler_version = ">=0.18.0"
type = "lib"

[dependencies]
aztec = { path = "../aztec" }
protocol_types = { git="https://github.com/AztecProtocol/aztec-packages", tag="aztec-packages-v0.17.0", directory="yarn-project/noir-protocol-circuits/src/crates/types" }